
name: frontend_files

services:
  db:
    container_name: frontend_files-db
    build: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - prism_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: frontend_files-api
    build: ./api
    ports:
      - "${API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - prism_network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://api:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  prism_network:
    driver: bridge